import "./globals.css";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
      title: "Tax Registration Services | Fintax Partners",

    description:
        "Professional GST registration and taxation compliance services for startups and businesses.",

    keywords: [
        "GST registration",
        "tax services",
        "business taxation",
        "CA services",
    ],
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <Header />

        {children}
        
        <Footer/>
        </body>
    </html>
  );
}
